Enforce formatting in `bin/test-unit`
- ensures that code has been formatted with `bin/format`

diff --git a/bin/test-unit b/bin/test-unit
--- a/bin/test-unit
+++ b/bin/test-unit
@@ -3,11 +3,15 @@ set -eu -o pipefail
 
 ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
 
-reformatted_packages="$(go fmt $(go list github.com/cloudfoundry/bosh-cli/... | grep -v /vendor/))"
-
-if [[ $reformatted_packages = *[![:space:]]* ]]; then
-  echo "go fmt reformatted the following packages:"
-  echo $reformatted_packages
+echo -e "\n Checking formatting..."
+files_needing_reformat="$("${ROOT_DIR}/bin/format" -l)"
+if [[ ${files_needing_reformat} = *[![:space:]]* ]]; then
+  echo "Error: some files require formatting (below)"
+  echo "${files_needing_reformat}"
+  echo "Error: some files require formatting (above)"
+  echo "=> run 'bin/format -w' to reformat with 'goimports'"
+  echo "   see: https://pkg.go.dev/golang.org/x/tools/cmd/goimports"
+  exit 1
 fi
 
 echo -e "\n Running linter..."
