Add fmt, vet, and lint to the test suite
Signed-off-by: Adam Stegman <astegman@pivotallabs.com>

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,7 +1,27 @@
 #!/bin/bash
 
-set -e
-
 bin=$(dirname $0)
 
-exec $bin/env ginkgo -r -race $@
+echo -e "\n Formatting packages..."
+$bin/go fmt github.com/cloudfoundry/bosh-micro-cli/...
+let "result+=$?"
+
+echo -e "\n Vetting packages for potential issues..."
+$bin/go vet github.com/cloudfoundry/bosh-micro-cli/...
+let "result+=$?"
+
+echo -e "\n Checking with golint..."
+$bin/golint
+let "result+=$?"
+
+echo -e "\n Testing packages..."
+$bin/env ginkgo -r -race $@
+let "result+=$?"
+
+if [ $result -eq 0 ]; then
+  echo -e "\n\033[0;32mSUITE SUCCESS\033[0m"
+else
+  echo -e "\n\033[0;31mSUITE FAILURE\033[0m"
+fi
+
+exit $result
